---
title: "The pulsatile user's guide"
author: Matt Mulvahill (matthew.mulvahill@ucdenver.edu)
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    code_folding: show
vignette: >
  %\VignetteIndexEntry{The pulsatile user's guide}
  %\VignetteEngine{rmarkdown::render}
  %\VignetteEncoding{UTF-8}
---



# Introduction



```{r options, echo=FALSE}
library(knitr)
opts_chunk$set(echo       = TRUE,
               message    = TRUE,
               warning    = TRUE,
               eval       = TRUE)
```

```{r load-package}
install.packages("devtools")
library(devtools)
install_github("mmulvahill/pulsatile")
library(pulsatile)
library(ggplot2)
```

```{r simulate-pulse}
set.seed(9999)
this_pulse <- simulate_pulse()
str(this_pulse)

ggplot(this_pulse$data, aes(x = time, y = concentration)) +
  geom_path()

```

```{r fit-pulse}
# These args are not yet implemented
model_spec <- pulse_spec(location_prior_type = "order-statistic")
fit_test   <- fit_pulse(.data = this_pulse, iters = 5000, thin = 50,
                        spec = model_spec)

```



# Session Info

```{r sessionInfo}
sessionInfo()
```




